riscv-software-src/riscv-unified-db

.github/workflows/regress.yml, bin/build_container, bin/setup, cfgs/generic_rv64/arch_overlay/csr/marchid.yaml
=> Add regression test action

arch/ext/I.yaml, arch/inst/A/amoadd.d.yaml, arch/inst/A/amoadd.w.yaml, arch/inst/A/amoand.d.yaml, arch/inst/A/amoand.w.yaml, arch/inst/A/amomax.d.yaml, arch/inst/A/amomax.w.yaml, arch/inst/A/amomaxu.d.yaml, arch/inst/A/amomaxu.w.yaml, arch/inst/A/amomin.d.yaml, arch/inst/A/amomin.w.yaml, arch/inst/A/amominu.d.yaml, arch/inst/A/amominu.w.yaml, arch/inst/A/amoor.d.yaml, arch/inst/A/amoor.w.yaml, arch/inst/A/amoswap.d.yaml, arch/inst/A/amoswap.w.yaml, arch/inst/A/amoxor.d.yaml, arch/inst/A/amoxor.w.yaml, arch/isa/builtin_functions.idl, arch/isa/globals.isa, arch/isa/util.idl, cfgs/generic_rv64/params.yaml, lib/arch_def.rb, lib/idl/ast.rb
Also adds params to properly handle the configurable priority of Misaligned/Access/Page faults
=> Add Zaamo instructions.

.github/workflows/pages.yml, README.adoc
=> Add RVA/MC-1 pdf generation to GitHub actions, link off README

backends/crd_doc/templates/crd.adoc.erb, backends/manual/templates/instruction.adoc.erb, backends/profile_doc/templates/profile_pdf.adoc.erb, lib/arch_obj_models/instruction.rb
=> Add exception analysis back in generators

arch/crd/MC-1.yaml, arch/crd/MockCRD-1.yaml, backends/crd_doc/tasks.rake, backends/crd_doc/templates/crd.adoc.erb, lib/arch_obj_models/crd.rb, lib/arch_obj_models/schema.rb
Assuming this passes the regression test (running now), you'll want to merge this into main.
=> Fixing bugs we worked on earlier today.

lib/arch_obj_models/csr.rb, lib/arch_obj_models/csr_field.rb
=> Fix optional calc

.github/workflows/pages.yml, .gitignore, Rakefile, arch/crd/MC-1.yaml, arch/crd/MockCRD-1.yaml, arch/crd_family/MockCRDFamily.yaml, arch/profile/MockProfile-1.yaml, arch/profile/rva20s64.yaml, arch/profile/rva20u64.yaml, arch/profile/rva22s64.yaml, arch/profile/rva22u64.yaml, arch/profile_family/MockProfileFamily.yaml, arch/profile_family/rva.yaml, backends/crd_doc/templates/crd.adoc.erb, backends/portfolio_doc/tasks.rb, backends/portfolio_doc/templates/family_intro.erb, backends/profile_doc/tasks.rake, backends/profile_doc/templates/profile.adoc.erb, lib/arch_def.rb, lib/arch_obj_models/crd.rb, lib/arch_obj_models/portfolio.rb, lib/arch_obj_models/profile.rb
=> Created common base class called "Portfolio" that both Profiles and CRDs use.

arch/certificate_model/MockCertificateModel.yaml, arch/ext/MockExt.yaml, arch/profile_class/RVA.yaml, arch/profile_release/MockProfileRelease.yaml, backends/certificate_doc/tasks.rake, backends/certificate_doc/templates/certificate.adoc.erb, backends/manual/templates/instruction.adoc.erb, backends/profile_doc/tasks.rake, backends/profile_doc/templates/profile.adoc.erb, lib/arch_def.rb, lib/arch_obj_models/certificate.rb, lib/arch_obj_models/extension.rb, lib/arch_obj_models/portfolio.rb, lib/arch_obj_models/profile.rb
Created new class ExtensionPresence and now generate profiles either with or without different kinds of optional.
Is the extension mandatory, optional, various kinds of optional, etc.
Accepts two kinds of YAML schemas:
String
Example => presence: mandatory
Hash
Must have the key "optional" with a String value
Example => presence:
optional: development
class ExtensionPresence
=> Different kinds of optional

arch/inst/C/c.lui.yaml, lib/arch_obj_models/instruction.rb
=> fix duplicate `not` keyword

arch/csr/I/mcounteren.layout, arch/csr/I/mcounteren.yaml
=> Fix bug in mcounteren.CY

backends/ext_pdf_doc/templates/ext_pdf.adoc.erb
=> Fix CSR headings in ext_pdf backend

arch/inst/B/rori.yaml
Fixed the encoding for `rori`.
=> Fixed rori.yaml encoding

.devcontainer/devcontainer.json, .pre-commit-config.yaml, schemas/arch_schema.json, schemas/config_schema.json, schemas/csr_schema.json, schemas/ext_schema.json, schemas/inst_schema.json, schemas/manual_version_schema.json, schemas/schema_defs.json
relates to #260 and #267
Draft until #266 lands
=> add json related pre-commit hooks

arch/isa/fp.idl
In the future we need to document the dev environment and also add the github action for running pre-commit so dev's see this problems before they land in main.
=> fix pre-commit issues from last commit

.pre-commit-config.yaml
IMO none of these python checks are controversial:
- id: check-ast
- id: check-builtin-literals
- id: check-case-conflict
- id: check-docstring-first
And they all passed with the existing python code base.
=> add python specific pre-commit checks

lib/yaml_resolver.py
=> convert f-string termination to single-quote to fix syntax errors

.github/workflows/nightly.yml, .github/workflows/pages.yml, .github/workflows/regress.yml
fixed for these issues flagged by actionlint: 
```
❯ actionlint -ignore  "SC2102"
.github/workflows/nightly.yml:16:15: the runner of "actions/checkout@v2" action is too old to run on GitHub Actions. update the action's version to fix this issue [action]
|
16 |       - uses: actions/checkout@v2
|               ^~~~~~~~~~~~~~~~~~~
.github/workflows/nightly.yml:24:9: shellcheck reported issue in this script: SC2046:warning:1:9: Quote this to prevent word splitting [shellcheck]
|
24 |         run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
|         ^~~~
.github/workflows/nightly.yml:24:14: workflow command "set-output" was deprecated. use `echo "{name}={value}" >> $GITHUB_OUTPUT` instead: …
```
=> updating actions to latest versions

cfgs/qc_iu/arch_overlay/ext/Xqci.yaml
Xqci extension: fix change list of version 0.5 to include information about renamed instructions
=> Xqciv0p5p1: Xqci extension: fix change list of version 0.5 to include information about renamed instructions

.github/workflows/regress.yaml, .github/workflows/regress.yml, cfgs/qc_iu/arch_overlay/csr/Xqccmp/qc.mstkbottomaddr.yaml, cfgs/qc_iu/arch_overlay/csr/Xqccmp/qc.mstktopaddr.yaml, cfgs/qc_iu/arch_overlay/ext/Xqccmp.yaml, cfgs/qc_iu/arch_overlay/inst/Xqccmp/qc.cm.pop.yaml, cfgs/qc_iu/arch_overlay/inst/Xqccmp/qc.cm.popret.yaml, cfgs/qc_iu/arch_overlay/inst/Xqccmp/qc.cm.popretz.yaml, cfgs/qc_iu/arch_overlay/inst/Xqccmp/qc.cm.push.yaml, cfgs/qc_iu/arch_overlay/inst/Xqccmp/qc.cm.pushfp.yaml
- Fix all push and pop instructions description for RV64 (IDL code fix)
- Fix qc.cm.pushfp instruction to avoid rlist == 4, since not saving s0 == fp but updating it, should not occur
- Add CSRs qc.mstkbottomaddr and qc.mstktopaddr to support cache range checking
- Add list of supported custom exceptions - stack alignment check and stack range check
- Add stack exception checks in all push/pop instructions
=> Xqccmp Extension version 0.2

bin/setup
Fixed an error in the setup script where the ROOT command was not found. The syntax for DOCKER_BASE was updated from 
```
$(ROOT) to ${ROOT}
```
to correctly reference the environment variable in the Bash file, ensuring proper mounting of directories within the Docker container.
=> Resolve setup file error

arch/inst/Zcmp/cm.pop.yaml, arch/inst/Zcmp/cm.popret.yaml, arch/inst/Zcmp/cm.popretz.yaml, arch/inst/Zcmp/cm.push.yaml
Need to take in account that xlen() returns bits and not bytes
=> Zcmp extension: fix IDL code

arch_overlay/qc_iu/ext/Xqccmp.yaml, arch_overlay/qc_iu/inst/Xqccmp/qc.cm.pop.yaml, arch_overlay/qc_iu/inst/Xqccmp/qc.cm.popret.yaml, arch_overlay/qc_iu/inst/Xqccmp/qc.cm.popretz.yaml, arch_overlay/qc_iu/inst/Xqccmp/qc.cm.push.yaml, arch_overlay/qc_iu/inst/Xqccmp/qc.cm.pushfp.yaml, arch_overlay/qc_iu/isa/globals.isa
changes:
- Fix all push and pop instructions IDL code to take in consideration that xlen() returns bits and not bytes
- Declare state of extension as "frozen"
=> Xqccmp extension: version 0.3 

arch_overlay/qc_iu/ext/Xqccmp.yaml, arch_overlay/qc_iu/ext/Xqci.yaml, arch_overlay/qc_iu/ext/Xqcicm.yaml, arch_overlay/qc_iu/inst/C/c.slli.yaml, arch_overlay/qc_iu/inst/Xqccmp/qc.cm.mva01s.yaml, arch_overlay/qc_iu/inst/Xqccmp/qc.cm.mvsa01.yaml, arch_overlay/qc_iu/inst/Xqccmp/qc.cm.pop.yaml, arch_overlay/qc_iu/inst/Xqccmp/qc.cm.popret.yaml, arch_overlay/qc_iu/inst/Xqccmp/qc.cm.popretz.yaml, arch_overlay/qc_iu/inst/Xqccmp/qc.cm.push.yaml, arch_overlay/qc_iu/inst/Xqccmp/qc.cm.pushfp.yaml, arch_overlay/qc_iu/inst/Xqci/qc.c.muliadd.yaml, arch_overlay/qc_iu/inst/Xqci/qc.c.mveqz.yaml
around extensions conflicts management, as well correct hint support for additional 16-bit instructions
=> Xqci/Xqccmp extensions: more fixes 

arch/inst/B/rorw.yaml
The YAML for the RORW instruction has shamt as an operand. shamt is used as an immediate value, but the RORW instruction uses a register value. The RISC-V ISA specification shows the analogous RORW instruction's operand is named rs2, which is appropriate here.
Change RORW operand shamt to rs2.
Also, in the IDL for RORW, the shamt _value_ should be retrieved from rs2 (not rs1, as is done currently.
Fix the retrieval of the shamt value to come from rs2. 
closes #478
=> Fix RORW operand and IDL

arch_overlay/qc_iu/inst/Xqci/qc.c.muliadd.yaml, arch_overlay/qc_iu/inst/Xqci/qc.c.mveqz.yaml
X[reg] with reg = creg2reg(rd) is used for accessing the source operand rs1.
I believe this is a bug.
=> arch_overlay/qc_iu: Fix bug in qc.c.muliadd/qc.c.mveqz

lib/arch_obj_models/obj.rb
Should fix ext_pdf generation issue with missing instructions.
=> Ensure that ext req expression satisfiability accounts for ext absence

arch_overlay/qc_iu/ext/Xqciint.yaml, cfgs/qc_iu.yaml
from cfgs/qc_iu to Xqciint extension.
currently supported only as part of extension.
=> Xqci/Xqciint extension: move extension codes 

arch_overlay/qc_iu/ext/Xqci.yaml, arch_overlay/qc_iu/ext/Xqcia.yaml, arch_overlay/qc_iu/ext/Xqcibm.yaml, arch_overlay/qc_iu/ext/Xqcicli.yaml, arch_overlay/qc_iu/ext/Xqciint.yaml, arch_overlay/qc_iu/ext/Xqcilo.yaml, arch_overlay/qc_iu/ext/Xqcilsm.yaml, arch_overlay/qc_iu/inst/Xqci/qc.c.mnret.yaml, arch_overlay/qc_iu/inst/Xqci/qc.c.mret.yaml, arch_overlay/qc_iu/inst/Xqci/qc.e.lb.yaml, arch_overlay/qc_iu/inst/Xqci/qc.e.lh.yaml, arch_overlay/qc_iu/inst/Xqci/qc.ext.yaml, arch_overlay/qc_iu/inst/Xqci/qc.extd.yaml, arch_overlay/qc_iu/inst/Xqci/qc.extdpr.yaml, arch_overlay/qc_iu/inst/Xqci/qc.extdprh.yaml, arch_overlay/qc_iu/inst/Xqci/qc.extdr.yaml, arch_overlay/qc_iu/inst/Xqci/qc.extdupr.yaml, arch_overlay/qc_iu/inst/Xqci/qc.extduprh.yaml, arch_overlay/qc_iu/inst/Xqci/qc.extdur.yaml, arch_overlay/qc_iu/inst/Xqci/qc.lieq.yaml, arch_overlay/qc_iu/inst/Xqci/qc.norm.yaml, arch_overlay/qc_iu/inst/Xqci/qc.normeu.yaml, arch_overlay/qc_iu/inst/Xqci/qc.normu.yaml, arch_overlay/qc_iu/inst/Xqci/qc.setwm.yaml
changes:
- Fix IDL code sign extension logic for qc.e.lb and qc.e.lh instructions
- Fix IDL code sign extension logic for qc.ext and qc.extd instructions
- Fix IDL code sign extension logic for qc.extdpr, qc.extdprh and qc.extdr instructions
- Fix IDL code and description increasing shift to 6 bit for qc.extdr and qc.extdur instructions
- Fix IDL code and description increasing shift to 6 bit for qc.extdpr and qc.extdprh instructions
- Fix IDL code and description increasing shift to 6 bit for qc.extdupr and qc.extduprh instructions
- Fix IDL code sign extension logic for qc.lieq instruction
- Fix wrong mantissa bit selection in qc.norm, qc.normu and qc.normeu instructions
- Fix wrong exponent calculation in qc.normeu instruction
- Fix IDL code and description of qc.setwm instruction to …
=> Xqci Extension v0.9

arch/csr/hstatus.yaml, arch/csr/mie.yaml, lib/arch_obj_models/csr_field.rb, lib/arch_obj_models/obj.rb, lib/idl/ast.rb, schemas/csr_schema.json, schemas/schema_defs.json
Adds an array form of "description" fields that enables tagged statements.
In this first cut, statements can be tagged as:
- normative or non-normative.
- conditional, using an IDL function to evaluate the condition
=> schema: add array form of description

arch/ext/H.yaml
Added extra_validation to enforce `NUM_EXTERNAL_GUEST_INTERRUPTS` <= 31 when `SXLEN` == 32 as in #619.
=> Fix for H.yaml

backends/common_templates/adoc/inst.adoc.erb, backends/instructions_appendix/templates/instructions.adoc.erb, backends/manual/templates/instruction.adoc.erb, lib/arch_obj_models/instruction.rb, lib/template_helpers.rb
Add string to hexa conversion methods on instructions. Update the templates to follow the new style. Outputs appear with a number-per-cell format now.
=> Enhance wavedrom display to a number-per-cell format. 

arch/inst/Zk/aes32dsi.yaml, arch/inst/Zk/aes32dsmi.yaml
This PR is to add the missing `long_name` and `description`  in some of the YAML files as @AFOliveira shared.
=> Add long_name and description to AES instructions

arch/ext/Zawrs.yaml
The latest version of the spec shows Zawrs as version 1.0.1, not 1.1.0.
=> Fix Zawrs extension version (1.0.1 vs 1.1.0)

backends/manual/templates/playbook.yml.erb
relates to #646
Default antora bundle zip pulling in template links remove those by overriding in playbook
looks like this now: 
In the future we could probably put useful links in the top nav, but for now this just removes the useless ones.
=> data: remove bad top nav links from antora site

.pre-commit-config.yaml
fixes #645
previously looked at all files and didn't consider the case of dirty files that won't be committed or gitignored which is a common case
=> fix: change reuse lint pre-commit hook to only look at committed files

.github/workflows/regress.yml
This will allow dependabot to bump LLVM version (hopefully) while keeping the cached json when no bump happens.
=> fix(ci): fix caching on LLVM instruction test to allow bumping

ext/auto-inst/test_parsing.py
since compiler and ISA view of the instruction differ
Fixes #460
=> fix: skip fence.tso on llvm-test

schemas/manual_schema.json, schemas/manual_version_schema.json
fixes #709
done to remove anti-pattern which could have caused problems if code using schema assumed type with const but it wasn't defined that way
=> refactor: remove type from jsonschema when const defined

arch_overlay/qc_iu/inst/Xqccmp/qc.cm.popret.yaml, arch_overlay/qc_iu/inst/Xqccmp/qc.cm.popretz.yaml
> JSON Schema Validation Error for inst/Xqccmp/qc.cm.popretz.yaml: 'Destroy function call stack frame, move zero to `a0` and return to `ra`.' does not match '.*[^.!,]$'
=> fix(data): remove '.' at end of 'long_name's

arch/ext/S.yaml
The existing description said 
> This parameter only has an effect when both S and F mode are disabled.
This is incorrect. The field has an effect when F is disabled and S is enabled. We could update the description, but the preceding line makes this sentence redundant anyway, so this just removes the line instead.
The same issue applies to the "vs" field.
=> Fix mstatus fs/vs field descriptions

lib/deploy.sh
Commit 4ddb999 added some nice logging, but also added a lot of quotes. A few too many, in fact, as this:
```
./do gen:html_manual MANUAL_NAME=isa VERSIONS=all
```
became:
```
deploy_do "gen:html_manual MANUAL_NAME=isa VERSIONS=all"
```
The quotes there turn "command argument argument" into a single command string where the spaces are part of the command itself.
Remove the quotes so that the arguments are again treated as arguments.
=> fix: too much quoting in `lib/deploy.sh`

.github/workflows/regress.yml
riscv.json is llvm-tablegen for risc-v.
Uploading it to github actions, allows users to download it, instead of building it locally.
=> feat(llvm-test): upload riscv.json to github

arch/inst/Zicsr/csrrc.yaml, arch/inst/Zicsr/csrrci.yaml, arch/inst/Zicsr/csrrsi.yaml, arch/inst/Zkn/aes64ks1i.yaml, arch/inst/Zkn/aes64ks2.yaml, arch/inst/Zknd/aes64ds.yaml, arch/inst/Zknd/aes64dsm.yaml, arch/inst/Zknd/aes64im.yaml, arch/inst/Zkne/aes64es.yaml, arch/inst/Zkne/aes64esm.yaml
This PR adds missing long_name and description to the following AES and CSR instructions:
- aes64ks1i
- aes64ks2
- es64ds
- aes64dsm
- aes64im
- aes64es
- aes64esm
- csrrc
- csrrci
- csrrsi
=> Add long_name and description to AES and CSR instructions

arch/inst/V/vfmv.f.s.yaml
=> fix(data): fix assembly field introduced in wrong llvm parsing

backends/manual/templates/instruction.adoc.erb
just make synopsis implicit by removing header
and putting inst.description at top of page
fixes #745
=> feature: condense overview section of inst pg tmpl

arch/csr/H/htimedeltah.yaml, arch/csr/minstreth.yaml
Most "upper half" CSRs are already defined "base: 32"...
except "htimedeltah" and "minstreth". Fix them.
BREAKING CHANGE: Some "upper half" CSRs no longer available to RV64.
CSRs "htimedeltah" and "minstreth" were mistakenly available to RV64.
They will no longer be available to RV64.
=> fix(data): All "upper half" CSRs are RV32-only

arch_overlay/qc_iu/inst/Xqci/qc.e.lb.yaml, arch_overlay/qc_iu/inst/Xqci/qc.e.lbu.yaml, arch_overlay/qc_iu/inst/Xqci/qc.e.lh.yaml, arch_overlay/qc_iu/inst/Xqci/qc.e.lhu.yaml, arch_overlay/qc_iu/inst/Xqci/qc.e.lw.yaml
Otherwise loads from negative offsets such as
qc.e.lw a0, -0x8004(a0)
won't work correctly.
=> Xqci: Make sure `imm` is signed for extended loads

.github/dependabot.yml
Seems like this would be a better cadence than daily 
weekly happens on monday
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#interval
=> chore: change dependabot submodule check to weekly

arch/csr/misa.yaml, arch/ext/Q.yaml
This pull request introduces the following changes:
- Added a new field `Q` in `arch/csr/misa.yaml` to indicate support for the Q (quad precision float) extension.
- Introduced a new parameter `MUTABLE_MISA_Q` in `arch/ext/Q.yaml`.
- Changes to `F` and `D` bits might be required. Looking forward to getting some feedback on this.
**Related Issue:**
- Issue #788
=> feat: add misa Q bit, add MUTABLE_MISA_Q parameter to Q extension

arch/inst/C/c.add.yaml, arch/inst/C/c.addw.yaml, arch/inst/C/c.and.yaml, arch/inst/C/c.or.yaml, arch/inst/C/c.sub.yaml, arch/inst/C/c.subw.yaml, arch/inst/C/c.xor.yaml, arch/inst/F/froundnx.s.yaml, arch/inst/Zfh/flh.yaml, arch/inst/Zfh/fli.h.yaml, arch/inst/Zfh/fsh.yaml, arch/inst/Zicfiss/ssrdp.yaml, arch/inst/Zilsd/sd.yaml, backends/instructions_appendix/all_instructions.golden.adoc
- `rd` to `xd`
- `rs1` to `xs1`
- `rs2` to `xs2`
Fix a few cases where a `$` appeared before the register name.
Add a few missing "long_names".
=> fix(data): fix remaining old register names

arch/inst/D/fld.yaml, arch/inst/D/fsd.yaml, arch/inst/F/flw.yaml, arch/inst/F/fsw.yaml, arch/inst/Q/flq.yaml, arch/inst/Q/fsq.yaml, arch/inst/Zfh/flh.yaml, backends/instructions_appendix/all_instructions.golden.adoc
- make sure the loads load to a float register
- make sure the stores store from a float register
- update the corresponding field names, description, IDL
- make sure the assembly syntax are correct
- add a few missing "long_name"
- remove an extraneous `$`
=> fix(data): floating-point loads/stores several issues

arch/inst/C/c.nop.yaml, arch/inst/Zicsr/csrrs.yaml, arch/inst/Zicsr/csrrw.yaml, arch/inst/Zicsr/csrrwi.yaml
- `c.nop` has no operands
- For CSR instructions, `imm` should be `csr` to better match Sail
- Correct operand order and names
=> fix(data): correct assembly in a few places

.pre-commit-config.yaml
This is ok to land before #811 because it just doesn't find any of the files until then.
=> chore: add pre-commit jsonschema check for profile_family & profile_release

arch/inst/C/c.addi16sp.yaml, arch/inst/C/c.addi4spn.yaml, arch/inst/C/c.ldsp.yaml, arch/inst/C/c.lwsp.yaml, arch/inst/C/c.sdsp.yaml, arch/inst/C/c.swsp.yaml, arch/inst/Zcd/c.fldsp.yaml, arch/inst/Zcd/c.fsdsp.yaml, arch/inst/Zcf/c.flwsp.yaml, arch/inst/Zcf/c.fswsp.yaml
PR #804 removed the `(sp)` operand from stack-pointer-based instructions. This change was motivated by comparing the assembly with the RISC-V Sail model.
Unfortunately, the Sail model was incorrect in comparison to the RISC-V spec, the spec being the current "single source of truth".
Add the stack pointer operand back to these instructions.
Fixes issue #833.
=> fix(data): stack-pointer instruction assembly needs stack-pointer

arch/inst/Zcd/c.fld.yaml, arch/inst/Zcd/c.fldsp.yaml, arch/inst/Zcd/c.fsd.yaml, arch/inst/Zcd/c.fsdsp.yaml, arch/inst/Zcf/c.flw.yaml, arch/inst/Zcf/c.flwsp.yaml, arch/inst/Zcf/c.fsw.yaml, arch/inst/Zcf/c.fswsp.yaml, backends/instructions_appendix/all_instructions.golden.adoc
Old register names are being used in some places for
description, assembly, fields.
Related to https://github.com/riscv/sail-riscv/pull/1049
Fixes #843
=> fix(data): correct floating point register names in places

backends/instructions_appendix/all_instructions.golden.adoc, spec/std/isa/inst/B/andn.yaml, spec/std/isa/inst_opcode/OP.yaml
In (#686), a new instruction schema was created
for types/subtypes. This commit change B/andn
instruction to use the new schema. It is also part of effort in (#655).
=> andn: use the new instruction schema

spec/std/isa/inst/B/clmul.yaml, spec/std/isa/inst/B/clmulh.yaml, spec/std/isa/inst/B/orn.yaml, spec/std/isa/inst/B/rol.yaml, spec/std/isa/inst/B/rolw.yaml, spec/std/isa/inst/B/ror.yaml, spec/std/isa/inst/B/rorw.yaml, spec/std/isa/inst/B/xnor.yaml
In (#686), a new instruction schema was created
for types/subtypes. This commit changes B/clmul,
B/clmulh, B/orn, B/rol, B/rolw, B/ror, B/rorw,
B/xnor instructions to use the new schema. They
all are of the same subtypes. It is also part of
effort in (#655).
=> inst/B: use the new instruction schema

.github/workflows/merge.yml, .github/workflows/regress.yml
This adds a workflow that should run when a PR is added to the merge queue. The workflow has all the same jobs that run to deploy pages. This is step 1 of a full fix; step two is to deploy using the same GitHub actions instead of the deploy.sh script.
=> feat(ci): add GitHub merge workflow

.github/workflows/merge.yml, .github/workflows/regress.yml
This should let us make sure PRs fail in the merge queue if they fail to build a deployment target
=> feat: make all deploy actions dry-run from regress

.github/workflows/merge.yml
Take 2; the first attempt didn't work because the 'dry-run' input isn't in scope when triggered from the merge queue.
=> feat: get deploy actions running in both merge queue and regress

tools/ruby-gems/udb/lib/udb/obj/database_obj.rb
Using `to_s` on a `T::Enum` like `kind` returns the object reference (e.g., `#<DatabaseObject::Kind::Profile>`) instead of the actual string value.
Replaced `to_s` with `serialize`, which correctly returns the string value (e.g., `"profile"`).
`serialize` is the intended way to extract string values from `T::Enum`. 
Fixes #853
=> fix: printing object string in profile extension appendix

spec/std/isa/csr/H/henvcfg.yaml, spec/std/isa/csr/H/henvcfgh.yaml, spec/std/isa/csr/menvcfg.yaml, spec/std/isa/csr/menvcfgh.yaml
The ADUE field type() logic was backwards in all environment configuration CSRs.
Fixed logic:
- When Svadu IS implemented  ADUE field is Read-Write (software control)
- When Svadu is NOT implemented  ADUE field is Read-Only-0 (hardwired)
Closes #1026
=> fix: correct Svadu ADUE field type logic in environment CSRs

spec/schemas/proc_cert_class_schema.json, spec/schemas/proc_cert_model_schema.json, spec/schemas/profile_family_schema.json, spec/schemas/profile_release_schema.json, spec/schemas/profile_schema.json
Removes unnecessary "type" from schema definition when a "const" is declared. 
This prevents problem where code using the jsonschema makes the type mandatory like here: https://github.com/riscv-software-src/riscv-unified-db/issues/636
fixes #1015
=> refactor: remove unneeded type in jsonschema when const defined

bin/setup
- Change default behavior to always recreate .bundle/config
- Users will now always get configuration updates
- Add --preserve-config option for backward compatibility
- Add --help option for usage information
- Fix argument processing conflicts when script is sourced by other tools
- Prioritizes reliability over performance concerns 
- Addresses overly cautious guard that prevented config updates
- Uses sir @rpsene's argument parsing approach with improved defaults
Fixes #980
Ready for Review sir @ThinkOpenly sir @dhower-qc sir @christian-herber-nxp
=> fix: always recreate bundle config by default #980

backends/instructions_appendix/all_instructions.golden.adoc, spec/std/isa/inst/C/c.slli.yaml, spec/std/isa/inst/C/c.srai.yaml, spec/std/isa/inst/C/c.srli.yaml
In all the other instructions the destination register is named xd, not rd, except the shift instructions.
Furthermore in the assembly attribute of the shift instructions the destination register is designated as xd, not rd,
thus causing code generators to generate incorrect code.
=> fix inconsistent destination register naming in compressed shift instructions

.github/workflows/pages.yml
Workflow action "pages" is failing:
```
cp doc/udb-block.svg _site/ && ruby -r erb -r date
-e "File.write('_site/index.html',
ERB.new(File.read('tools/scripts/pages.html.erb'),
trim_mode: '-').result(binding))"
shell: /usr/bin/bash -e {0}
env:
SINGULARITY: 1
PAGES_URL: https://riscv-software-src.github.io/riscv-unified-db
/home/runner/work/_temp/66305e27-873c-44c3-94d0-8903895f3902.sh: line 4: -e: command not found
```
I think the line invoking Ruby needs to be all on one logical line.
=> ci: fix deploy pages workflow error

backends/instructions_appendix/all_instructions.golden.adoc, spec/std/isa/inst/Sdext/dret.yaml, spec/std/isa/inst/Smdbltrp/sctrclr.yaml, spec/std/isa/inst/Smrnmi/mnret.yaml, spec/std/isa/inst/Zvbb/vwsll.vi.yaml, spec/std/isa/inst/Zvkned/vaeskf1.vi.yaml, spec/std/isa/inst/Zvkned/vaeskf2.vi.yaml, spec/std/isa/inst/Zvks/vsm3c.vi.yaml, spec/std/isa/inst/Zvks/vsm4k.vi.yaml
- `dret`, `mnret`, and `sctrclr` take no operands.
- ~~`sspush` and `sspopchk` are each single mnemonics that take a very
restricted set of operand values.
Also include a bit of documentation.~~
- `vaeskf1.vi`, `vaeskf2.vi`, `vsm3c.vi`, `vsm4k.vi`, `vwsll.vi`:
renamed field to match operand.
=> fix(data): fix field names to be closer to operands

spec/std/isa/isa/util.idl
This PR fixes #473.
The ```lowest_set_bit``` and ```highest_set_bit``` functions were returning XReg (i.e., Bits<XLEN>) though they only compute a position index. Updated to return Bits<8> instead, which is sufficient and semantically correct.
All smoke tests and IDL validations pass successfully.
@ThinkOpenly please review this and request if any further chnaged are required !!
=> FIXES ISSUE #473 : lowest/highest_set_bit functions should return a Bits type?

tools/ruby-gems/udb/lib/udb/cli.rb
Adds an option to choose the output file for `./bin/udb list extensions`. The default is still stdout. This mirrors the option that already exists for `./bin/udb list parameters`.
=> feat: add output option to udb list extensions
