riscv-software-src/riscv-unified-db

Gemfile, Gemfile.lock
**may require './bin/bundle' to be run on existing clones**
fixes #43
=> Fix font issue in PDF generation

.github/workflows/regress.yml
Added PDF build of MC-1 and RVA profile to regression
=> Added PDF build of MC-1 and RVA profile to regression

backends/crd_doc/templates/crd.adoc.erb, lib/arch_obj_models/extension.rb, lib/arch_obj_models/schema.rb, lib/template_helpers.rb
Derek, can you merge this into main if it builds okay? I want to have a link to the updated MC-1 CRD for tomorrow's (as I write this on Tuesday evening) Microcontroller WG.
=> Better display of extension parameters (mainly links).

arch/csr/H/hcounteren.layout, arch/csr/H/hcounteren.yaml
=> Fix typo in hcounteren

lib/idl/passes/reachable_exceptions.rb
=> Make reachable exception pass look for raise_precise, too

backends/arch_gen/tasks.rake
=> Make arch gen stamps dependent on object model

backends/profile_doc/tasks.rake
=> Fix rake dependence on arch def for profile gen

arch/isa/globals.isa
=> Fix typo in Pbmt enum

lib/arch_obj_models/obj.rb
=> Indent SchemaCondition asciidoc list

schemas/config_schema.json, schemas/csr_schema.json, schemas/ext_schema.json, schemas/implemented_exts_schema.json, schemas/json-schema-draft-07.json
=> Avoid using internet for schema fetch

lib/template_helpers.rb
=> Add render() to TemplateHelpers

backends/common_templates/adoc/README.adoc, backends/common_templates/adoc/csr.adoc.erb, backends/common_templates/adoc/inst.adoc.erb, backends/ext_pdf_doc/templates/ext_pdf.adoc.erb, lib/arch_obj_models/extension.rb, lib/template_helpers.rb, views/html/README.md
This will allow template re-use for asciidoc.
closes #59
=> Add partial templates

arch/inst/F/fadd.s.yaml
Brought up here: https://github.com/riscv-software-src/riscv-unified-db/pull/295#issuecomment-2558345768
=> Fix merge conflict resolve on #295 that overwrote change for #334

.pre-commit-config.yaml, lib/yaml_resolver.py
relates to #394
all changes in py code are just from running the pre-commit hooks
=> install python fmt pre-commit hooks

arch/inst/I/jalr.yaml
=> Clarify jalr description and IDL

arch/inst/F/fadd.s.yaml, arch/inst/F/fsub.s.yaml, arch/isa/fp.idl
- Added function and IDL for floating point subtraction.
- Added descriptions and long names for floating point addition and subtraction.
=> Floating point addition and subtraction code addition

.devcontainer/Dockerfile, backends/cpp_hart_gen/renode/udb.resc, bin/setup, container.def
Fixes and minor improvements to Renode-based cpp_hart flow
=> Cpp hart fixups

arch_overlay/qc_iu/ext/Xqci.yaml, arch_overlay/qc_iu/ext/Xqciint.yaml, arch_overlay/qc_iu/inst/Xqci/qc.c.mienter.nest.yaml, arch_overlay/qc_iu/inst/Xqci/qc.c.mienter.yaml, arch_overlay/qc_iu/inst/Xqci/qc.c.mileaveret.yaml
changes:
- Add stack checks to qc.c.mienter, qc.c.mienter.nest, qc.c.mileaveret
=> Xqci v0.8 additional fixes

arch_overlay/qc_iu/isa/globals.isa
restore get_and_validate_stack_pointer function with correct checks
=> Xqccmp/Xqci qc_iu configuration

.pre-commit-config.yaml, bin/asciidoctor, bin/bash, bin/build_container, bin/bundle, bin/clean, bin/node, bin/npx, bin/pip, bin/pre-commit, bin/python, bin/ruby, bin/setup, do
fixes #495
relates to #493, #494
Currently only flagging shellcheck errors.  There's more warning to work thru if we want later (most around quoting vars)
shfmt runs w/o any corrections so this will just continue that could practice.
=> add shell script fmt and lint with pre-commit checks and fix errors

.pre-commit-config.yaml
because of #520 error running in sigularity
and waiting on #523 to finalize real fix
=> disable shellcheck temporarily

Gemfile, Gemfile.lock
=> point at github commit for updated ruby-prof dep

arch_overlay/qc_iu/ext/Xqci.yaml, arch_overlay/qc_iu/ext/Xqcibm.yaml, arch_overlay/qc_iu/inst/Xqci/qc.extdur.yaml, arch_overlay/qc_iu/inst/Xqci/qc.insbh.yaml, arch_overlay/qc_iu/inst/Xqci/qc.insbhr.yaml
- fix some representation issues
- fix qc.extdur rs1 != 31
=> Xqci/Xqcibm extension fixes 

.pre-commit-config.yaml, backends/cpp_hart_gen/cpp/include/udb/bits.hpp
Also ran `pre-commit run --all-files` and new version of clang-fmt changed one file
=> task: update pre-commit hook repo versions

.pre-commit-config.yaml
done with `pre-commit autoupdate`
also ran `pre-commit run --all-files` to make sure everything still passes and no changes
=> task: update git hook repo versions

arch_overlay/qc_iu/ext/Xqci.yaml, arch_overlay/qc_iu/ext/Xqciint.yaml, arch_overlay/qc_iu/inst/Xqci/qc.c.mileaveret.yaml
changes:
- Fix IDL code for Smdbltrp and Smrnmi spec compatibility for qc.c.mileaveret instruction
=> Xqci extension version 0.10.0

arch/isa/globals.isa, arch/profile/RVB23U64.yaml, backends/certificate_doc/templates/certificate.adoc.erb, backends/cpp_hart_gen/cpp/include/udb/bits.hpp, backends/cpp_hart_gen/cpp/include/udb/csr.hpp, backends/cpp_hart_gen/cpp/include/udb/defines.hpp, backends/cpp_hart_gen/cpp/include/udb/version.hpp, backends/cpp_hart_gen/cpp/src/libhart_renode.cpp, backends/cpp_hart_gen/cpp/test/test_bits.cpp, backends/cpp_hart_gen/cpp/test/test_version.cpp, backends/cpp_hart_gen/lib/gen_cpp.rb, backends/cpp_hart_gen/lib/template_helpers.rb, backends/cpp_hart_gen/templates/enum.cxx.erb, backends/cpp_hart_gen/templates/hart.hxx.erb, backends/cpp_hart_gen/templates/libhart.h.erb, backends/cpp_hart_gen/templates/libhart_renode.h.erb, lib/arch_obj_models/instruction.rb, lib/arch_obj_models/obj.rb, lib/arch_obj_models/portfolio.rb, lib/cfg_arch.rb, lib/config.rb, lib/idl/ast.rb, lib/idl/type.rb, schemas/inst_schema.json
=> task: fix typos

arch/csr/misa.yaml
https://github.com/riscv/riscv-isa-manual/blob/main/src/machine.adoc
=> fix: misa[M,S,U,V] wrong offset bits

backends/isa_explorer/isa_explorer.rb
=> chore: fix url to point to UDB GH pages and now CSC

.github/workflows/regress.yml, backends/cpp_hart_gen/tasks.rake, lib/arch_obj_models/parameter.rb
=> fix(cpp): re-add functions deleted by #584

.github/workflows/regress.yml
Normal regression test for the new ouput.
Missing on previous PR and noticed by @jordancarlin.
=> feat(CI): add c_header generation to regression test

arch/inst/C/c.ldsp.yaml, arch/inst/C/c.lwsp.yaml, arch/inst/C/c.sdsp.yaml, arch/inst/C/c.swsp.yaml, arch/inst/Zcd/c.fldsp.yaml, arch/inst/Zcd/c.fsdsp.yaml, arch/inst/Zcf/c.flwsp.yaml, arch/inst/Zcf/c.fswsp.yaml
=> fix(data): stack pointer instructions have no stack pointer parameter

.vscode/launch.json, arch/profile_family/Mock.yaml, arch/profile_family/RVA.yaml, arch/profile_family/RVB.yaml, arch/profile_family/RVI.yaml, arch/profile_release/Mock.yaml, arch/profile_release/RVA20.yaml, arch/profile_release/RVA22.yaml, arch/profile_release/RVA23.yaml, arch/profile_release/RVB23.yaml, arch/profile_release/RVI20.yaml, backends/profile/tasks.rake, backends/profile/templates/profile.adoc.erb, lib/arch_obj_models/database_obj.rb, lib/arch_obj_models/portfolio.rb, lib/arch_obj_models/profile.rb, lib/architecture.rb, schemas/profile_family_schema.json
=> chore: renamed profile class to profile family

backends/instructions_appendix/all_instructions.golden.adoc, package-lock.json, spec/std/isa/inst/Zicbom/cbo.inval.yaml
=> fix(bug): fixed type of excepetion cbo.inval should throw when mode!=M and menvfg.CBIE==0

spec/std/isa/inst/Zimop/mop.r.n.yaml, tools/ruby-gems/udb/lib/udb/obj/instruction.rb
=> refactor: remove redundant assignment of run

tools/scripts/pages.html.erb
Closes #1075 and #1080 (duplicate)
=> fix: isa_explorer spreadsheet
